// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrodeEstudiantesFernandoCalderon.Datos;

#nullable disable

namespace RegistrodeEstudiantesFernandoCalderon.Migrations
{
    [DbContext(typeof(RegistroDBContext))]
    [Migration("20260812151951_EstudianteCursoOptional")]
    partial class EstudianteCursoOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaMatricula")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Estudiante", b =>
                {
                    b.HasOne("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Curso", "CursoActual")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CursoActual");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Matricula", b =>
                {
                    b.HasOne("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Curso", "CursoActual")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Estudiante", "EstudianteActual")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CursoActual");

                    b.Navigation("EstudianteActual");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Profesor", b =>
                {
                    b.HasOne("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Curso", "CursoActual")
                        .WithMany("Profesores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CursoActual");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Curso", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("Matriculas");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("RegistrodeEstudiantesFernandoCalderon.RegistrodeEstudiantes.Estudiante", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
